src/apps/config_management/urls.py
from django.urls import path

from . import views

app_name="config_management"
urlpatterns = [
    path("", views.index, name="index"),
    path("configuration/", views.configuration, name="configuration"),
]

src/apps/tasks/urls.py
from django.urls import path

from . import views

app_name="tasks"
urlpatterns = [
    path("sync/", views.sync, name="sync"),
    path("tasks/", views.tasks, name="tasks"),
    path("tasks/503", views.page_503, name="tasks-503"),
    path("tasks/404", views.page_404, name="tasks-404"),
]

src/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.config_management.urls", namespace="cfg")),
    path("", include("apps.permission_management.urls", namespace="perm")),
    path("", include("apps.authentication.urls", namespace="auth")),
    path("", include("apps.tasks.urls", namespace="tasks")),
]

src/djtest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("helloapp.urls")),
    path("admin/", admin.site.urls),
]

src/helloapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("editparams/", views.editparams, name="editparams"),
    path("components/", views.components, name="components"),
]

src/apps/tasks/models.py
from django.db import models
from django.db.models.query import QuerySet

from datetime import datetime as dttm
import requests
import logging
import json

from core.settings import AIRFLOW_HOST, AIRFLOW_PORT

logger = logging.getLogger(__name__)

HEADERS = {
    "Content-Type": "application/json",
    "Accept": "application/json"
}

AIRFLOW_URL = f"http://{AIRFLOW_HOST}:{AIRFLOW_PORT}"

AUTH = ('admin', 'admin')

CONN_TIMEOUT = 1


class DagRun:
    def __init__(self, dag_run_json):
        self.dag_run_id = dag_run_json.get("dag_run_id")
        self.dag_id = dag_run_json.get("dag_id")
        self.logical_date = dag_run_json.get("logical_date")
        self.start_date = dag_run_json.get("start_date")
        self.end_date = dag_run_json.get("end_date")
        self.data_interval_start = dag_run_json.get("data_interval_start")
        self.data_interval_end = dag_run_json.get("data_interval_end")
        self.last_scheduling_decision = dag_run_json.get("last_scheduling_decision")
        self.run_type = dag_run_json.get("run_type")
        self.state = dag_run_json.get("state")
        self.external_trigger = dag_run_json.get("external_trigger")
        self.conf = dag_run_json.get("conf")
        self.note = dag_run_json.get("note")

    
class TaskInstance:
    def __init__(self, ti_json):
        self.task_id = ti_json.get("task_id")
        self.dag_id = ti_json.get("dag_id")
        self.dag_run_id = ti_json.get("dag_run_id")
        self.execution_date = ti_json.get("execution_date")
        self.start_date = ti_json.get("start_date")
        self.end_date = ti_json.get("end_date")
        self.duration = ti_json.get("duration")
        self.state = ti_json.get("state")
        self.try_number = ti_json.get("try_number")
        self.map_index = ti_json.get("map_index") 
        self.max_tries = ti_json.get("max_tries") 
        self.hostname = ti_json.get("hostname") 
        self.unixname = ti_json.get("unixname") 
        self.pool = ti_json.get("pool") 
        self.pool_slots = ti_json.get("pool_slots") 
        self.queue = ti_json.get("queue") 
        self.priority_weight = ti_json.get("priority_weight") 
        self.operator = ti_json.get("operator")
        self.queued_when = ti_json.get("queued_when")
        self.pid = ti_json.get("pid")
        self.executor_config = ti_json.get("executor_config")
        self.sla_miss = ti_json.get("sla_miss")
        self.rendered_fields = ti_json.get("rendered_fields")
        self.trigger = ti_json.get("trigger")
        self.triggerer_job = ti_json.get("triggerer_job")
        self.note = ti_json.get("note")



def get_request(url, headers=HEADERS, out='json') -> str | dict:
    formats = ['text', 'json']
    if out not in formats:
        raise ValueError(f'The get_request function only supports the following output formats: {formats}.')

    response = requests.get(url, headers=headers, auth=AUTH, timeout=CONN_TIMEOUT) # request


    if response.status_code == requests.codes.not_found:
        raise NameError(json.loads(response.text)["detail"]) 
    elif response.status_code != requests.codes.ok: # check responce
        raise Exception(json.loads(response.text)["detail"]) 
    
    if out=='text':
        return response.text
    else:
        return json.loads(response.text)


class Dag(models.Model):
    dag_id = models.CharField(primary_key=True, max_length=100)
    name = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    @property
    def tasks(self) -> QuerySet["Task"]:
        return self.task_set.all()
    

    @property
    def __queue_elements(self) -> QuerySet["QueueElement"]:
        return self.queue_element_set.all()
    

    @property
    def __next_queue_elements(self) -> QuerySet["QueueElement"]:
        return self.queue_element_set_next.all()


    @property
    def next_dag(self):
        queue = self.__queue_elements.first()
        if queue:
            return queue.dag_id_next
        else:
            return None
        
    
    @property
    def prev_dag(self):
        queue = self.__next_queue_elements.first()
        if queue:
            return queue.dag_id_previous
        else:
            return None


    def get_info_about_dag(self):
        url = f"{AIRFLOW_URL}/api/v1/dags/{self.dag_id}"
        return get_request(url)



    def get_last_dag_run(self, after_date=dttm.fromisoformat("2023-01-01T00:00:00Z")) -> DagRun:
        url = f"{AIRFLOW_URL}/api/v1/dags/{self.dag_id}/dagRuns?limit=1"
        total_dag_runs = int(get_request(url)["total_entries"])
        
        offset = 0
        if total_dag_runs > 0:
            offset = total_dag_runs - 1

        dag_runs = get_request(url+f"&offset={offset}")["dag_runs"]

        last_dag_run = {}

        if len(dag_runs) > 0:
            last_dag_run = dag_runs[-1]
            if dttm.fromisoformat(last_dag_run["logical_date"]) < after_date:
                return None

        return DagRun(last_dag_run)


    def get_dag_run(self, dag_run_id) -> DagRun:
        url = f"{AIRFLOW_URL}/api/v1/dags/{self.dag_id}/dagRuns/{dag_run_id}"
        return DagRun(get_request(url))


    def get_task_instances(self, dag_run_id) -> list[TaskInstance]:
        url = f"{AIRFLOW_URL}/api/v1/dags/{self.dag_id}/dagRuns/{dag_run_id}/taskInstances"
        tis = get_request(url)["task_instances"]
        return list([TaskInstance(ti) for ti in tis])


    def is_active(self, after_date=dttm.fromisoformat("2023-01-01T00:00:00Z")) -> bool:
        return self.get_last_dag_run(after_date).state in ["queued", "running"]


    def get_target_info(self, dag_run_id, ext_dag_ids=[], ext_task_ids=[]):
        dag_run = self.get_dag_run(dag_run_id)
        task_instances = self.get_task_instances(dag_run_id)

        start_time = dttm.fromisoformat(dag_run.logical_date) \
            .strftime("%b %d, %Y, %I:%M:%S %p")
        tasks_total = self.tasks.count()
        ti_total = len(list(
            filter(lambda ti: ti.state == "success", task_instances)
        ))

        tasks = []
        dag_duration = 0.0
        for task in self.tasks:
            task_instance:TaskInstance
            for ti in task_instances:
                if ti.task_id == task.task_id:
                    task_instance = ti
                    break
            duration = task_instance.duration
            if duration:
                dag_duration += float(duration)

        if self.dag_id in ext_dag_ids:
            for task in self.tasks:

                task_instance:TaskInstance
                for ti in task_instances:
                    if ti.task_id == task.task_id:
                        task_instance = ti
                        break

                
                duration = task_instance.duration
                state = task_instance.state
                if state is None:
                    state = "no_status"
                if duration:
                    duration = f"{round(float(duration), 2)}s"

                logs = ["Waiting for logs", ]

                if task.task_id in ext_task_ids:
                    logs = task.get_logs(dag_run_id, try_num=1, out='list')

                tasks.append({
                    "id": task.task_id,
                    "name": task.name,
                    "state": state,
                    "duration": duration,
                    "logs": logs,
                })
        else:
            for task in self.tasks:
                tasks.append({ "id": task.task_id })

        task = {
            "id": self.dag_id,
            "name": self.name,
            "state": dag_run.state, 
            "time": start_time, 
            "duration": f"{round(dag_duration, 2)}s",
            "total_steps": tasks_total,
            "completed_steps": ti_total,
            "subtasks": tasks
        }

        return task


    def pause(self):
        payload = {
            "is_paused": True,
        }
        url = f"{AIRFLOW_URL}/api/v1/dags/{self.dag_id}"
        is_paused = False

        while not is_paused:
            response = requests.patch(url, headers=HEADERS, auth=AUTH, json=payload)
            if response.status_code == requests.codes.not_found:
                False
            if response.status_code != requests.codes.ok:
                return False
            is_paused = json.loads(response.text)["is_paused"]

        return True
    

    def resume(self):
        payload = {
            "is_paused": False,
        }
        url = f"{AIRFLOW_URL}/api/v1/dags/{self.dag_id}"
        is_paused = True

        while is_paused:
            response = requests.patch(url, headers=HEADERS, auth=AUTH, json=payload)
            if response.status_code != requests.codes.ok:
                return False
            is_paused = json.loads(response.text)["is_paused"]

        return True
    

    def trigger(self, conf={}) -> str:
        payload = {
            "conf": conf,
        }

        if not self.resume():
            return False

        # trigger dag
        url = f"{AIRFLOW_URL}/api/v1/dags/{self.dag_id}/dagRuns"
        response = requests.post(url, headers=HEADERS, auth=AUTH, json=payload)
        
        if response.status_code == requests.codes.not_found:
            raise NameError(json.loads(response.text)["detail"]) 
        if response.status_code != requests.codes.ok:
            raise Exception(json.loads(response.text)["detail"])

        dag_run_id = json.loads(response.text)["dag_run_id"]
        
        return dag_run_id


    def clear(self, dag_run_id) -> bool:
        payload = {
            "dry_run": False,
        }
        url = f"{AIRFLOW_URL}/api/v1/dags/{self.dag_id}/dagRuns/{dag_run_id}/clear"
        response = requests.post(url, headers=HEADERS, auth=AUTH, json=payload)

        if response.status_code == requests.codes.not_found:
            raise NameError(json.loads(response.text)["detail"]) 

src/apps/tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import JsonResponse, HttpRequest, HttpResponse

from requests.exceptions import ConnectionError

from apps.config_management.models import File
from .request_handler import SyncRequestHandler, TasksRequestHandler
from .globals import SPN, RIPN, ROPN, RTYPE, QUEUE_ID
from .task_manager import TaskManager
from .models import Dag, Queue
from apps.decorators import no_running_tasks_required

from datetime import datetime as dttm

import logging

logger = logging.getLogger(__name__)


@login_required(login_url=reverse_lazy("auth:login"))
def page_503(request: HttpRequest):
    return render(request, "tasks/page-503.html")

@login_required(login_url=reverse_lazy("auth:login"))
def page_404(request: HttpRequest):
    return render(request, "tasks/page-404.html", status=404)


@login_required(login_url=reverse_lazy("auth:login"))
def tasks(request: HttpRequest):
    request_handler = TasksRequestHandler(request)
    w_request = request_handler.w_request

    if w_request.is_ajax and w_request.method_is_post:

        match w_request.ajax_type:

            case RTYPE.ABORT | RTYPE.RESTART: 
                request_handler.handle_task_action(w_request.ajax_type)

            case _:
                request_handler.handle_unknown_request_type()

    elif w_request.is_ajax and w_request.method_is_get:

        match w_request.ajax_type:

            case RTYPE.SHOW_LOGS:
                request_handler.handle_show_logs()

            case RTYPE.UPDATE_STATE:
                request_handler.handle_update_state() 

            case _:
                request_handler.handle_unknown_request_type()

    elif not w_request.is_ajax and w_request.method_is_post:
        request_handler.handle_post()

    elif not w_request.is_ajax and w_request.method_is_get:
        request_handler.handle_get()
        
    else:
        request_handler.handle_not_implemented()

    return request_handler.response


@login_required(login_url=reverse_lazy("auth:login"))
@no_running_tasks_required(redirect_url=reverse_lazy("tasks:tasks"))
def sync(request: HttpRequest):
    request_handler = SyncRequestHandler(request)
    w_request = request_handler.w_request

    if w_request.method_is_post:
        request_handler.handle_post()
    elif w_request.method_is_get:
        request_handler.handle_get()
    else:
        request_handler.handle_not_implemented()

    return request_handler.response

src/apps/templates/tasks/page-404.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="bg-light min-vh-100 d-flex flex-row align-items-center">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="clearfix">
            <h1 class="float-start display-3 me-4">404</h1>
            <h4 class="pt-3">Not found!</h4>
            <p class="text-medium-emphasis">The Dag required for synchronization was not found in the Airflow service.</p>
          </div>
          <div class="input-group">
            <span class="input-group-text">
              <svg class="icon">
                <use xlink:href="/static/assets/icons/common-icons.svg#home"></use>
              </svg>
            </span>
            <a class="btn btn-info" type="button" href="{% url 'cfg:index' %}">Go to home</a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

src/apps/templates/tasks/page-503.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Error 503 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="bg-light min-vh-100 d-flex flex-row align-items-center">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="clearfix">
            <h1 class="float-start display-3 me-4">503</h1>
            <h4 class="pt-3">Service Unavailable!</h4>
            <p class="text-medium-emphasis">Completing tasks is temporarily unavailable. Unable to connect to Airflow.</p>
          </div>
          <div class="input-group">
            <span class="input-group-text">
              <svg class="icon">
                <use xlink:href="/static/assets/icons/common-icons.svg#home"></use>
              </svg>
            </span>
            <a class="btn btn-info" type="button" href="{% url 'cfg:index' %}">Go to home</a>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

src/apps/templates/tasks/sync.html
{% extends "layouts/base.html" %}

{% block title %} Tasks {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
    
  <link href="/static/assets/vendors/@coreui/chartjs/css/coreui-chartjs.css" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}

  <div class="container-fluid d-flex flex-column flex-fill">
    
    <div class="row justify-content-between bg-black bg-gradient header mb-4">
      <div class="rounded col-4" id="Header">
        <h4 class="text-light display-6">Stale сonfigurations</h4>
      </div>
    </div>

    <div class="row flex-fill ms-md-5 ps-md-5 me-md-5 pe-md-5">
      <div class="col-lg">
        {% include './includes/stale-resources.html' %}
      </div>
    </div>

    <div class="row justify-content-between footer footer-sticky bg-black bg-gradient">
      <div class="col-sm-auto text-center ms-md-5 ps-md-5">
        <a 
          type="button" 
          class="btn btn-primary btn-lg"
          id="back-btn"
          href="{% url 'cfg:configuration' %}"
        >Back</a>
      </div>
      <div class="col-sm-auto text-center me-md-5 pe-md-5">
        <form action="{% url 'tasks:sync' %}" method="post"
        {% if not is_conn_good or not has_dags %}
        data-coreui-toggle="tooltip"
        data-coreui-placement="top" 
        {% endif %}
        {% if not is_conn_good %}
        title="Synchronization is temporarily unavailable. Can't connect to Airflow service."
        {% elif not has_dags %}
        title="Synchronization is temporarily unavailable. Synchronization dags not found."
        {% endif %}
        >
          {% csrf_token %}
          <!-- Button sync -->
          {% if is_conn_good and has_dags %}
          <input class="btn btn-primary btn-lg" type="submit" value="Sync resources">
          {% else %}
          <input class="btn btn-primary btn-lg disabled" type="submit" value="Sync resources">
          {% endif %}
        </form>
      </div>
    </div>
  </div>
  

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

    <!-- Plugins and scripts required by this view-->
    <script src="{{ STATIC_URL }} /static/jquery-3.7.1.min.js"></script>
    <script src="/static/assets/vendors/chart.js/js/chart.min.js"></script>
    <script src="/static/assets/vendors/@coreui/chartjs/js/coreui-chartjs.js"></script>
    <script src="/static/assets/vendors/@coreui/utils/js/coreui-utils.js"></script>
    <script src="/static/assets/js/main.js"></script>

    <script src="/static/js/helpers.js"></script>
    <script>activate_tooltips();</script>
  
{% endblock javascripts %}

src/apps/templates/tasks/tasks.html
{% extends "layouts/base-only-footer.html" %}

{% block title %} Tasks {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}
    
  <link href="/static/assets/vendors/@coreui/chartjs/css/coreui-chartjs.css" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}

  <div class="container-fluid d-flex flex-column flex-fill ps-5 pe-5 pt-4">
    <div class="row-auto ms-md-5 ps-md-5 me-md-5 pe-md-5 mb-4"> 
      <span class="display-5">Synchronizing configuration changes</span>
    </div>
    

    {% include './includes/tasks-list.html' %}


    
    {% include 'includes/toast-saved.html' %} 
  </div>
  <div class="justify-content-between footer footer-sticky bg-light pe-md-5 ps-md-5">
    <div class="col-sm-auto text-center ms-md-5 ps-md-5">
      <form action="{% url 'tasks:tasks' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="type" value="back">
        <input 
          type="submit"
          class="btn btn-primary btn-lg disabled"
          id="back-btn"
          value="Back">
      </form>
    </div>
    <div class="col-sm-auto text-center me-md-5 pe-md-5">
      <form action="{% url 'tasks:tasks' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="type" value="finish">
        <input 
          type="submit"
          class="btn btn-primary btn-lg disabled"
          id="finish-btn"
          value="Finish">
      </form>
    </div>
  </div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

  <!-- Plugins and scripts required by this view-->
  <script src="{{ STATIC_URL }} /static/jquery-3.7.1.min.js"></script>
  <script src="/static/assets/vendors/chart.js/js/chart.min.js"></script>
  <script src="/static/assets/vendors/@coreui/chartjs/js/coreui-chartjs.js"></script>
  <script src="/static/assets/vendors/@coreui/utils/js/coreui-utils.js"></script>
  <script src="/static/assets/js/main.js"></script>

  <script src="/static/js/globals.js"></script>
  <script src="/static/js/exceptions.js"></script>
  <script src="/static/js/helpers.js"></script>
  <script src="/static/js/checkers.js"></script>
  <script src="/static/js/decorators.js"></script>
  <script src="/static/js/error-handlers.js"></script>
  <script src="/static/tasks/js/globals.js"></script>
  <script src="/static/tasks/js/helpers.js"></script>
  <script src="/static/tasks/js/handlers.js"></script>
  <script src="/static/tasks/js/main.js"></script>
  
{% endblock javascripts %}