src/apps/config_management/urls.py
from django.urls import path

from . import views

app_name="config_management"
urlpatterns = [
    path("", views.index, name="index"),
    path("configuration/", views.configuration, name="configuration"),
]

src/apps/permission_management/urls.py
from django.urls import path

from . import views

app_name="config_management"
urlpatterns = [
    path("permissions/", views.permissions, name="permissions"),
]

src/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.config_management.urls", namespace="cfg")),
    path("", include("apps.permission_management.urls", namespace="perm")),
    path("", include("apps.authentication.urls", namespace="auth")),
    path("", include("apps.tasks.urls", namespace="tasks")),
]

src/djtest/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("helloapp.urls")),
    path("admin/", admin.site.urls),
]

src/helloapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("editparams/", views.editparams, name="editparams"),
    path("components/", views.components, name="components"),
]

src/apps/templates/includes/alert-modal.html
<!-- Modal -->
<div 
  class="modal fade" 
  id="alertModal" 
  data-coreui-backdrop="static" 
  data-coreui-keyboard="false" 
  tabindex="-1" 
  aria-labelledby="staticBackdropLabel" 
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-scrollable modal-xl">
    <div class="modal-content" id="changes-modal-list">
      <div class="modal-header">
        <h5 class="modal-title" id="modalTitle">Are you sure?</h5>
        <button class="btn-close" type="button" data-coreui-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="modalBody">...</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" id="modalCancelBtn" data-coreui-dismiss="modal">Cancel</button>
        <button class="btn btn-primary" type="button" id="modalContinueBtn">Continue</button>
      </div>
    </div>
  </div>
</div>

src/apps/templates/includes/confirm-save-modal.html
<!-- Modal -->
<div 
  class="modal fade" 
  id="confirmSaveModal" 
  data-coreui-backdrop="static" 
  data-coreui-keyboard="false" 
  tabindex="-1" 
  aria-labelledby="staticBackdropLabel" 
  aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-scrollable modal-xl">
    <div class="modal-content" id="changes-modal-list">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmSaveModalLabel">Save changes?</h5>
        <button class="btn-close" type="button" data-coreui-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">...</div>
      <div class="modal-footer">
        <input class="form-control" placeholder="Enter commit message" id="commit-msg" type="text"/>
        <button class="btn btn-secondary" type="button" id="modal-close-btn" data-coreui-dismiss="modal">Close</button>
        <button class="btn btn-primary" type="button" id="save-changes-btn">{{ btn_text }}</button>
      </div>
    </div>
  </div>
</div>

src/apps/templates/includes/footer.html
<footer class="footer">
  <div class="ms-auto">&copy; 
    <a target="_blank" href="https://github.com/YARIK-AI/YARIK-Management">YARIK-Management</a> 
    - Configuration management interface.
  </div>
</footer>

src/apps/templates/includes/navigation.html
<header class="header header-sticky">
  <div class="container-fluid justify-content-between">
    <div class="d-flex align-items-center">
      <!--button class="header-toggler px-md-0 me-md-3" type="button" id="sidebar-toggler" disabled>
        <svg class="icon icon-lg">
          <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-menu"></use>
        </svg>
      </button-->
      <a class="header-brand d-none d-sm-block" href="">
        <svg width="150" height="50" alt="YARIK Management Logo" >
          <use xlink:href="/static/assets/brand/logo-no-background.svg#black-full"></use>
        </svg>
      </a>
      <ul class="nav nav-pills d-md-flex">
        <!--li class="nav-item"><a class="nav-link" aria-current="page" href="">Status</a></li-->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cfg:configuration' %}" id="configuration-nav-tab">Configuration</a>
        </li>
      </ul>
    </div>
    <ul class="header-nav ms-3">
      <li class="nav-item dropdown">
        <a 
          class="nav-link py-0" 
          data-coreui-toggle="dropdown" 
          href="" 
          role="button" 
          aria-haspopup="true" 
          aria-expanded="false"
        >
          <div class="avatar avatar-md">
            <svg width="30" height="30" alt="User">
              <use xlink:href="/static/assets/icons/common-icons.svg#user"></use>
            </svg>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-end pt-0">
          <div class="dropdown-header bg-light py-2">
            <div class="fw-semibold">{{ request.user.username }}</div>
          </div>
          {% if request.user.is_staff and request.user.is_active %}
          <a class="dropdown-item" href="{% url 'perm:permissions' %}">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
            </svg> Permissions
          </a> 
          {% endif %}
          <!--a class="dropdown-item" href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
            </svg> Profile
          </a>
          <a class="dropdown-item" href="#">
            <svg class="icon me-2">
              <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-settings"></use>
            </svg> Settings
          </a-->
          <div class="dropdown-divider"></div>
          <form action="{% url 'auth:logout' %}" method="post">
            {% csrf_token %}
            <button class="dropdown-item">
              <svg class="icon me-2">
                  <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
              </svg> Logout</button>
          </form>
        </div>
      </li>
    </ul>
  </div>
</header>

src/apps/templates/includes/scripts.html
<!-- CoreUI and necessary plugins-->
<script src="/static/assets/vendors/@coreui/coreui/js/coreui.bundle.min.js"></script>
<script src="/static/assets/vendors/simplebar/js/simplebar.min.js"></script>

src/apps/templates/includes/sidebar.html
{% extends "layouts/sidebar_base.html" %}

{% block sidebar_elements %}
  <li class="nav-item"><a class="nav-link" href="" id="home-sidebar-tab">
    <svg class="nav-icon text">
      <use xlink:href="/static/assets/icons/common-icons.svg#home"></use>
    </svg> Home</a></li>
  <li class="nav-item"><a class="nav-link" href="">
    <svg class="nav-icon">
      <use xlink:href="/static/assets/icons/common-icons.svg#cluster"></use>
    </svg> Clusters</a></li>
  <li class="nav-item"><a class="nav-link" href="">
    <svg class="nav-icon">
      <use xlink:href="/static/assets/icons/common-icons.svg#host"></use>
    </svg> Hosts</a></li>
{% endblock sidebar_elements %}

src/apps/templates/includes/toast-saved.html
<div class="toast-container position-fixed top-0 end-0 p-3">
  <div 
    class="toast align-items-center" 
    id="result-message-toast" 
    role="alert" 
    aria-live="assertive" 
    aria-atomic="true"
  >
    <div class="d-flex">
      <div class="toast-body">...</div>
      <button class="btn-close me-2 m-auto" type="button" data-coreui-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
</div>